# Netlify configuration for Single Page Application (SPA)

# Redirect rule for SPA routing:
# All paths that don't match an existing file should serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Build settings (adjust if needed)
[build]
  command = "npm run build" # Or yarn build, bun build
  publish = "dist"        # The directory containing the built site 